version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: cargo
  # Not yet supported. See <https://github.com/dependabot/dependabot-core/issues/4009>
  # versioning-strategy: "increase-if-necessary"
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: bytes
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: camino
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: clap
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: derivative
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: serde
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: shell-words
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: shellexpand
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: tempfile
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: thiserror
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: tokio
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: url
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: zip
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: '*'
    update-types:
    - version-update:semver-patch
  labels:
  - dependencies
