FROM rust:1.88.0-slim-bookworm AS build
ARG DEBIAN_FRONTEND=noninteractive

ADD . /app
WORKDIR /app
RUN apt-get update \
  && apt-get install -y pkg-config libssl-dev \
  && cargo build -p obo-cli --release

FROM debian:bookworm-slim
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y libssl3 ca-certificates \
  && rm -rf /var/lib/apt/lists/
COPY --from=build /app/target/release/obo /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/obo"]
